meta:
  title: "Example Book"
  author: "Example Author"
  isbn: "1234-5678"

# You can define buildPipelines if you want
# buildPipelines:
#   pdf:
#     - name: ejs
#     - name: markdown
#     - name: theme
